---
title: "Class 12: Web Scraping + LLM-based Extraction"
author: "Andrew Rauscher"
date: "2026-10-05"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    code_folding: show
    code_download: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PlanCrash Info Example

```{r crashes, results='hold'}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

# This should now print without the error
crash_page

crash_tables <- crash_page |>
  rvest::html_elements("table") |>
  rvest::html_table()

crash_df = crash_tables[[1]]

# From a cleaning perspective, there are several things that can be changed:
# [1] Replace the colnames with the first row
# [2] Have better column types (e.g., Date being a date instead of chr)
# [3] There are possible things you can do to clean the data within columns; e.g., split columns that contain multiple pieces of information
# Column 4 has: Fatalities/# passengers (ground fatalities)

# For today's class. we will focus on the first two
colnames(crash_df) = crash_df[1, ]
# then delete first row
crash_df = crash_df[-1, ]

crash_df = crash_df |>
  # Converts date into a date object
  dplyr::mutate(Date = lubridate::dmy(Date))
```

```{r salvage practice}

page = rvest::read_html("https://isa401-salvage.vercel.app/registry?start=1")
classes = page |>
  rvest::html_elements(".ship-class.Dreadnought") |>
  rvest::html_text2()
length(classes)   # check this first: one per card
```


```{r salvage practice cont.}
base = "https://isa401-salvage.vercel.app"
starts = seq(from = 1, to = 351, by = 50)
pages = vector("list", length(starts))
for (i in seq_along(starts)) {
  pg = rvest::read_html(paste0(base, "/registry?start=", starts[i]))
  pages[[i]] = data.frame(
    class = pg |> rvest::html_elements("div > ul > li:nth-child(1) > span") |>
      rvest::html_text2(),
    value = pg |> rvest::html_elements("div > ul > li:nth-child(3) > span") |>
      rvest::html_text2() |> stringr::str_remove(" MCr")
  )
  Sys.sleep(1)   # robots.txt asks for it
}
registry = dplyr::bind_rows(pages)   # 400 rows?

registry |> dplyr::filter(class == "Dreadnought") |>
  dplyr::mutate(value = as.numeric(value)) -> Dreadnoughts_df

sum(Dreadnoughts_df$value)
```


## Structured Text Extraction

### Course Information

```{r courses}
chat = ellmer::chat_openai(
  model = "gpt-5.6-luna", # note that the API Key that I provided only works with 5.6 luna
  params = ellmer::params(reasoning_effort = "none")
)

isa125_text = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |>
  # For this example, only the first course
  rvest::html_element("#sc_sccoursedescs > div:nth-child(1)") |> rvest::html_text2()


chat$chat_structured(
  isa125_text,
  type = ellmer::type_object(
    name = ellmer::type_string(
      description = "Name of the course. For example, ISA 235. Information Technology and the Intelligent Enterprise. Do not include the parantheses for the credit hour and do not end with a period"
    ),
    credit_hours = ellmer::type_integer(description = "Return the credit hours that are listed next to the course number and title in paranthesis"),
    description = ellmer::type_string(description = "The description of the course without the prereqs.")
  )
)
```


## All 50 courses

```{r coures50}

chat = ellmer::chat_openai(
  model = "gpt-5.6-luna", # note that the API Key that I provided only works with 5.6 luna
  params = ellmer::params(reasoning_effort = "none")
)

course_list = 
  rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |>
  rvest::html_elements("#sc_sccoursedescs > div") |> 
  rvest::html_text2() |> # returns a chr vector
  as.list() # so as.list() convers to a list to match the example in ...


  type_course = ellmer::type_object(
    name = ellmer::type_string(
      description = "Name of the course. For example, ISA 235. Information Technology and the Intelligent Enterprise. Do not include the parantheses for the credit hour and do not end with a period"
    ),
    credit_hours = ellmer::type_integer(description = "Return the credit hours that are listed next to the course number and title in paranthesis. Please do not include the parantheses in your response"),
    # Renamed description in desc to make it easier to see the description field from the element name (sublist name)
    desc = ellmer::type_string(description = "The description of the course without the prereqs."),
    preregs = ellmer::type_string("List the information after Prerequisite:")
  )
  
  isa_df = ellmer::parallel_chat_structured(
    chat = chat, prompts = course_list, type = type_course, include_tokens = T, include_cost = T
  )
```



















